language: csharp
solution: intacct-sdk-net.sln
mono: none
dotnet: 2.1.300
install:
- dotnet restore

script:
- dotnet build --configuration Release
- dotnet test Intacct.SDK.Tests/Intacct.SDK.Tests.csproj --framework "netcoreapp2.0"
- dotnet test Intacct.SDK.Tests/Intacct.SDK.Tests.csproj --framework "netcoreapp2.1"

notifications:
  slack:
    secure: D3WkYcHFpnZoB4rFlW8Ugj04qx5Dtp1UyeQ5XtUxU4Pf1Hfu3tN5rTrsafKPVPQ57ve0vNiUb7e1xV9+YUJvFBaNvh/zJaqEE9zGHYKlt4EfnDUktYBQJ8KE0FuW+OPIkAHye/e/D598OZNFRQV+m/0JYw7Yr4xQUl8SWqgMg6x6+lQo4W1L7kTxct4avUOJ9J0NcrCl52TaHRE0SkorooYu871+euzoLOYBs6bunypKN84GY51Bvlh9CcQDjau26TzP+AV/i5zfCnQE1ihl1N40zdmAPm9iZAswPYjQVSHPDikRTnOyo37t45/+JSgikhgB+JskTNE3Gc05JdPVwl6lvtISPt8xQLDc+faHFn3CDn2rSeS8gFRQ0dzpyVDotLQELcY95R566Yf6uCtI7q5W4txjPAxnsATRh2llfs7bWXMkRNu6Rm6zXCf8NcOO5K7TAR0I/j/Up9Bk8QMOg0/P1gzgyI/Ytne5iFTTyQTv7vBa0488P2kLfSpKEbCXmQQKoquuK1Nox6fW2H/jV1S5xIx26KnctFyHLBX1u6pM3+eFHDxOWAgiXIkMMDQddjzVuw/Lbt9QpJsN5ehAuvZ+ZwAlHkC5eOwmLmmwlySeyfGP3uCpqlidy+exEby70wm1v6yKKQJGpRRcosH2xXimJChAKrw1ORh2fP0cl1Q=
